# Generated by Django 3.0.7 on 2020-06-13 03:29

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reference',
            managers=[
                ('referenceList', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='reference',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255), max_length=255),
        ),
    ]
