# Generated by Django 3.0.7 on 2020-06-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_auto_20200613_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='slug',
            field=models.SlugField(max_length=255, unique_for_date='create'),
        ),
    ]
