# Generated by Django 3.0.7 on 2020-06-13 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0004_auto_20200613_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ('-publish',)},
        ),
        migrations.AlterModelManagers(
            name='reference',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='reference',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reference',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurnal_references', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reference',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
