# Generated by Django 3.0.7 on 2020-06-13 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0005_auto_20200613_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to=settings.AUTH_USER_MODEL),
        ),
    ]
